### ISSUE TITLE
Investigate data formats that live on-disk

### ISSUE THREAD

**Issue by caseyc37** [dolosse/dolosse#45]
# Description
We recognize that some of our users will need to travel with their data. For example, visiting scientists to a lab. In these scenarios it's critical that we provide a data storage format that they can copy onto a hard drive. There are a number of data formats available. We'll need to investigate further. 

# Format Requirements:
- Columnar storage
    - Enables us to take advantage of compression
    - We often return just a single column not an entire row.
    - ROOT Trees are row oriented, and we all know how much I (SVP) love those...
-  Good compression 
    - Our data often have repeated values (ex. channel, slot, crate, trace-out-of-range, etc.)
    - We'll need to transfer the files from place to place
- Compatible with [Spark](https://spark.apache.org/)
    - Spark will supercharge our pre-processing of the data
    - Also implies compatibility to other frameworks (e.g. hive)
- Compatible with Big Data stacks 
    - ex. Hadoop, MapR, Cloudera, etc.
    - We'll eventually be running on such systems anyway. 

# Options
## [Orc](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+ORC#LanguageManualORC-ORCFiles)

# Chosen format

**Comment by spaulaus** [comment]
@LindsD : I've updated this task with some of the research and investigations I've done. I spoke with @djfreels  and he'll be assisting. He's been doing similar investigations recently.

**Comment by spaulaus** [comment]
After a discussion w/ @djfreels , we've settled on Parquet. It's the format most compatible with Spark.
