### ISSUE TITLE
 Research into Central GUI for Control, Configuration and Visualization

### ISSUE THREAD

**Issue by AveshSook** [dolosse/dolosse#47]
Expected Behavior: Central Gui for control, configuration and visualization
Acceptance Criteria : 
- [ ] Control of DAQ from interface 
- [ ] Run Control
- [ ] Initialze system
- [ ] Set configurations
- [ ] Include all fuctionality of Root

**Comment by spaulaus** [comment]
@AveshSook we should look at https://dash.plot.ly/dash-daq
This should tie in well with the rest of the framework.

**Comment by spaulaus** [comment]
I think we can close this ticket. We'll use a tag team of angular8 and gridster2. Plotly provides the plotting. The other ACs are components in the dashboard. ROOT type analysis can be provided by a python backend.
